name: Generate and Upload Test File to Release

on:
  workflow_dispatch:

jobs:
  generate-and-upload:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate 1GB test file
      run: |
        # 生成一个 1GB 的文件
        dd if=/dev/zero of=testfile bs=1G count=1
        ls -lh testfile

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: test
        name: Test Release
        body: This is a test release containing a 1GB file.
        draft: false
        prerelease: false
        generate_release_notes: false

    - name: Upload 1GB test file to Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: test
        files: testfile