name: Upload Test Artifact

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  

      - name: Create test.txt
        run: |
          echo "hello world" > test.txt 

      - name: Upload test.txt as artifact
        uses: actions/upload-artifact@v3  
        with:
          name: test-file 
          path: test.txt   